### ISSUE TITLE
The output of a container stopping in a few seconds after starting is ignored

### ISSUE THREAD

**Issue by masm** [digital-wonderland/docker-logstash-forwarder#16]
As an example, I have a container that is started by cron to do backup using rsync. When there are no changes to update the backup, the containers stops in a couple of seconds. The output of this container is not forwarder and is effectivelly ignored. The container is not removed, so the output should still be available.

**Comment by digital-wonderland** [comment]
I would guess this happens because your container gets stopped again before the config gets generated & logstash-forwarder gets restarted in the first place.

The way docker-logstash-forwarder works, is that it waits ```$laziness``` seconds after receiving an event, that a container got started or stopped (configurable via the ```-laziness``` flag, see the [README](https://github.com/digital-wonderland/docker-logstash-forwarder/blob/master/README.md) - default is 5 seconds) before regenerating the config & restarting logstash-forwarder. So, if your container gets started & stopped within that timespan, it doesn't show up in the list of currently running containers and therefore its logs never get tailed.

This wouldn't be a bug but a feature. To change this you could run it with ```-laziness 0```.
