### ISSUE TITLE
Incremental tags

### ISSUE THREAD

**Issue by manuelmazzuola** [digital-wonderland/docker-logstash-forwarder#21]
Hello,
Can you use incremental tags instead tag every version with the `latest` string on docker hub ?
Is this a problem for you?

Cheers

**Comment by digital-wonderland** [comment]
Unfortunately I don't see this happening since it would require manual work on my part instead of just committing things.

I'm fully aware that the current setup isn't the most stable but I guess the old saying 'you get what you pay for' is true here as well. On the other hand it can only get better ...

**Comment by manuelmazzuola** [comment]
Ok, thank you anyway :+1:
