### ISSUE TITLE
Logs for short lived containers

### ISSUE THREAD

**Issue by CpuID** [digital-wonderland/docker-logstash-forwarder#25]
The readme states that after a restart, it only looks for running containers to start ingesting logs. Due to the way the laziness toggle works, this means if you have a short lived container (starts, completes a task, exits), it is possible for docker-logstash-forwarder to not see it after a restart as it is no longer running. This means you have some gaps in the exported logs of all containers for a server.

Would love to see a solution or workaround to this, open to suggestions or feedback :)

**Comment by CpuID** [comment]
My best guess solution is this would involve setting All: true here - https://github.com/digital-wonderland/docker-logstash-forwarder/blob/master/forwarder/forwarder.go#L41

In addition, would need to ensure logs that have already been ingested are ignored (as returning all containers could return items that have been stopped for days/weeks/months)

**Comment by digital-wonderland** [comment]
You can either set laziness to 0 so logstash-forwarder gets restarted immediately, but then very short lived containers might still get missed, or append something like ```sleep 10``` to whatever script you are running in your short lived container, to artificially prolong its lifespan, so its logs get picked up.

I wont add anything to try to handle that automatically - i.e. like you suggested above - since that will be just some source of bugs and would introduce a requirement of some external storage dependency.

Personally I would just go with appending ```sleep 10``` to scripts of short lived containers. Might look a bit strange but shouldn't have any downsides besides that and fixes the problem.

**Comment by CpuID** [comment]
Agreed re wanting to avoid a storage/state dependency where possible.

The other scenario of a short lived container though is one that errors out on startup, and you want the error logs sent to logstash. To still get these logs, we would need to sleep 10 all containers on start, which will delay rolling deploys amongst other things.

Would love to hear your thoughts on the above :)

**Comment by CpuID** [comment]
Hey @digital-wonderland any comments on my latest response at all?

**Comment by digital-wonderland** [comment]
I'm sorry, I got sidetracked and then forgot about it.

Anyways: What ```docker-logstash-forwarder``` does is simply generating a configuration for ```logstash-forwarder``` and then restarting an instance of it, after ```lazyness``` seconds, whenever it notices a change of running container.

For this to work the log file to be forwarded has to exist and the container must be running, which isn't the case anymore for short lived containers.

IIRC I read about some logging plugin for docker which is able to also forward application logs (instead of only stdout/stderr) but I can't find the link right now (it was from one of the Logging SaaS platforms). So writing a plugin specifically for Logstash should be possible.

Another option would be to use dockers syslog logging driver and also configure your applications to log to syslog. Then configure syslog to forward all logs to Logstash (which has a syslog input). This way any and all container logs should be captured, regardless how short lived the container is. Additional advantage would be that the hosts logs get captured as well.

If you are only interested in stdout/stderr getting forwarded dockers gelf driver would be an option too.

If it were me I guess I would currently go with the syslog approach since that captures everything (host, container stdout/stderr and application logs). Dunno if that is feasible for you?

I don't understand the part about having all containers to sleep for 10 seconds on start. I meant the short lived container should sleep for 10 seconds after it is done so its logs get picked up. That shouldn't delay any other containers?

**Comment by CpuID** [comment]
Thanks for the response @digital-wonderland - I think your on the right track :) I was doing some research yesterday and had similar opinions.

---

I agree something that uses a Docker logging driver would capture all containers, regardless of how long they live. This avoids the `lazyness` polling delay that exists in `docker-logstash-forwarder` currently, which has a purpose but polling vs event driven pushes being the difference here. I wonder if the Docker API has any support for long polling (or equivalent) on any endpoints...? That would allow some interesting capabilities.

I had considered the GELF docker logging driver, but the fact it is UDP only means it is potentially lossy. Running a full Logstash instance on each server is something I am trying to avoid, otherwise I could ingest GELF there and use a lumberjack output.

Another option is syslog, have the syslog docker logging driver send locally. Then forward from there. Definitely considering that road at the moment.

https://github.com/elastic/logstash/issues/3646#issuecomment-124731706 explains a bit more in detail the root issue at hand regarding lossy logs vs handling buffer sizes at the log source :)

---

The main issue re the sleep, is how do you introduce it "universally"? Would you ensure all Dockerfile's for all images run have a sleep in them somewhere? Would you have a post execution && entry on the CMD/ENTRYPOINT of something equivalent to if [ $? -ne 0 ]; then sleep 10; fi?

I am currently using Amazon ECS as a scheduler, which will spawn new containers as criteria sees fit. A failed container taking longer to fail than it has to, delays the startup of a replacement container and potentially could be service degrading depending how things are configured. At the same time, in theory if one container instance is failing to spawn, chances are all replacement instances are also failing, which does add merits to it.

My concern is more around failed containers (startup errors on PID 1) than single task short lived gracefully exiting containers also.

**Comment by digital-wonderland** [comment]
The API of [fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient) is actually event driven. The ```laziness``` parameter got only introduced to avoid the forwarder getting restarted _X_ times when I restart _X_ containers at the same time.

To introduce the sleeping thingy universally you could derive all your images from one base image of which you modify the shutdown routine. However, I understand your point and I agree with what you are saying. Also keep in mind that ```docker-logstash-forwarder``` got originally written cause I got tired of digging through logs in a console while playing around with CoreOS/Docker on a Macbook - as in I wouldn't use it in a production setting in its current for cause of its shortcomings.

For a production environment the only thing I would currently consider viable is using syslog since everything else is loosing more or less information/logs.

**Comment by CpuID** [comment]
No problem, thx for the feedback :)
